# Generated by Django 3.1 on 2021-04-28 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyitem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(null=True, upload_to='items/')),
                ('name', models.CharField(max_length=50)),
                ('provide', models.IntegerField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.brand')),
            ],
        ),
    ]
