# Generated by Django 3.1 on 2021-04-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_dailyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyitem',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
