# Generated by Django 3.1 on 2021-04-28 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_dailyitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.customer'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.IntegerField(),
        ),
    ]
