# Generated by Django 3.1 on 2021-04-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20210428_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='amt',
            field=models.FloatField(default=0),
        ),
    ]
