# Generated by Django 3.1 on 2021-04-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_auto_20210428_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='district',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='pin',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='purchase',
            name='street',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
