# Generated by Django 3.1 on 2021-04-29 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_auto_20210429_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amt', models.FloatField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('street', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('district', models.CharField(default=None, max_length=50)),
                ('pin', models.IntegerField(default=None)),
                ('status', models.IntegerField(default=0)),
                ('cid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.customer')),
            ],
        ),
        migrations.CreateModel(
            name='shoppingcart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('itid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.item')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.purchase')),
            ],
        ),
    ]
