# Generated by Django 3.1 on 2021-04-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0012_auto_20210429_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
