# Generated by Django 3.1 on 2021-04-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0013_auto_20210429_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
