# Generated by Django 3.1 on 2021-04-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0016_auto_20210430_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
