# Generated by Django 3.1 on 2021-05-03 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0017_auto_20210430_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyitem',
            old_name='provide',
            new_name='required',
        ),
        migrations.CreateModel(
            name='dailyrequired',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('got', models.IntegerField()),
                ('date', models.DateField()),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.dailyitem')),
            ],
        ),
    ]
