# Generated by Django 3.1 on 2021-05-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0018_auto_20210503_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyitem',
            name='photo',
        ),
        migrations.AlterField(
            model_name='dailyitem',
            name='required',
            field=models.IntegerField(default=0),
        ),
    ]
