# Generated by Django 3.1 on 2021-05-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0021_monthlysubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='item_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='itid',
            field=models.IntegerField(),
        ),
    ]
