# Generated by Django 3.1 on 2021-05-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0022_auto_20210505_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.customer')),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.dailyitem')),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlySubscribe',
        ),
    ]
