# Generated by Django 3.1 on 2021-05-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0023_auto_20210505_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
