# Generated by Django 3.1 on 2021-05-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0024_subscription_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('street', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('pin', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='city',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='district',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='street',
        ),
    ]
