# Generated by Django 3.1 on 2021-05-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0025_auto_20210506_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
