# Generated by Django 3.1 on 2021-05-06 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0026_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ad_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.purchase'),
        ),
    ]
