# Generated by Django 3.1 on 2021-05-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0027_auto_20210506_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='type',
        ),
    ]
