# Generated by Django 3.1 on 2021-05-06 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0028_remove_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='ad_id',
        ),
        migrations.AddField(
            model_name='address',
            name='sub_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.subscription'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='ad_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.address'),
        ),
    ]
