# Generated by Django 3.1 on 2021-05-06 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0029_auto_20210506_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='itid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tables.item'),
        ),
    ]
