# Generated by Django 3.1 on 2021-05-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0030_auto_20210506_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amt',
            field=models.FloatField(default=0),
        ),
    ]
