# Generated by Django 3.1 on 2021-05-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0031_subscription_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
