# Generated by Django 3.1 on 2021-05-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0032_subscription_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percent', models.FloatField()),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
            ],
        ),
    ]
