# Generated by Django 3.1 on 2021-05-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0033_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='min_amt',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
