# Generated by Django 3.1 on 2021-05-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0034_auto_20210515_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='storeitems',
        ),
    ]
