# Generated by Django 3.1 on 2021-05-18 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0035_auto_20210518_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='storeitems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('bid_date', models.DateField()),
                ('bid_start_time', models.TimeField()),
                ('bid_end_time', models.TimeField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.store')),
            ],
        ),
    ]
