# Generated by Django 3.1 on 2021-05-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0037_storeitems_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitems',
            name='price',
        ),
        migrations.AddField(
            model_name='storeitems',
            name='adid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.address'),
        ),
        migrations.AddField(
            model_name='storeitems',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.customer'),
        ),
        migrations.AddField(
            model_name='storeitems',
            name='min',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amt', models.FloatField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.customer')),
                ('stid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.storeitems')),
            ],
        ),
    ]
