# Generated by Django 3.1 on 2021-05-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0038_auto_20210518_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitems',
            name='photo',
            field=models.ImageField(null=True, upload_to='store/'),
        ),
    ]
