# Generated by Django 3.1 on 2021-05-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0039_auto_20210518_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amt',
            field=models.FloatField(null=True),
        ),
    ]
